// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Comment
{
    public int CommentId { get; set; }

    public int MemberId { get; set; }

    public DateTime DateCreate { get; set; }

    public string Content { get; set; }

    public string Picture { get; set; }

    public double Rate { get; set; }

    public int MilkId { get; set; }

    public virtual Member Member { get; set; }

    public virtual Milk Milk { get; set; }
}