// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int MemberId { get; set; }

    public int VoucherId { get; set; }

    public DateTime DateCreate { get; set; }

    public double Amount { get; set; }

    public string OrderStatus { get; set; } = string.Empty;

    public virtual Member Member { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Voucher Voucher { get; set; }
}