// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class User
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string Phone { get; set; }

    public DateTime DateOfBirth { get; set; }

    public string Gender { get; set; }

    public string Address { get; set; }

    public int RoleId { get; set; }

    public string ProfilePicture { get; set; }

    public DateTime DateCreate { get; set; }

    public virtual ICollection<Admin> Admins { get; set; } = new List<Admin>();

    public virtual ICollection<Member> Members { get; set; } = new List<Member>();

    public virtual Role Role { get; set; }

    public virtual ICollection<Staff> Staff { get; set; } = new List<Staff>();
}